spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?
    username: root
    password: yyb1emdrmq
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

#  file:
#    upload:
#      location: /Users/yyb40!/Desktop

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
